/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects known to DevMate */
        get: operations["listProjects"];
        put?: never;
        /** Register a local repository path as a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operational status for a project (connection, scan, defaults) */
        get: operations["getProjectStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a repository scan */
        post: operations["scanProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits for a branch, paginated by cursor */
        get: operations["listCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/commits/{commitHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single commit with its analysis */
        get: operations["getCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File tree at a commit */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only file content at a commit, optionally range-limited */
        get: operations["getFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structured diff for a file at a commit against its parent */
        get: operations["getFileDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List decisions */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/decisions/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a decision with its history */
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List open questions */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single question */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversation threads for a project */
        get: operations["listThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a thread, paginated by cursor */
        get: operations["listThreadMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/chat/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a chat run (assistant response), streamed via /runs/{runId}/events */
        post: operations["createChatRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/edit-proposals/{proposalId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write a previously proposed edit to disk, after explicit confirmation */
        post: operations["applyEditProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run status */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events stream of RunEvent (see src/features/chat/streaming/types.ts for the discriminated union) */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an in-flight run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured LLM providers */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single provider */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the default provider/model and per-task routing */
        put: operations["updateProviderSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured speech providers */
        get: operations["listSpeechProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available voices, optionally filtered by provider */
        get: operations["listVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/voices/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a short spoken sample for a voice */
        post: operations["previewVoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/speech/say": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Narrate arbitrary text with the project's configured speech provider/voice */
        post: operations["speakText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/settings/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Persist the selected speech provider/voice/rate */
        put: operations["updateSpeechSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/reading-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a reading session for a document */
        post: operations["createReadingSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a reading session */
        get: operations["getReadingSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading-sessions/{sessionId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop/checkpoint a reading session */
        post: operations["stopReadingSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reading-sessions/{sessionId}/segments/{index}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the audio for a single reading segment */
        get: operations["getReadingSegmentAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backend diagnostics snapshot */
        get: operations["getDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        ApiProblem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code?: string;
            requestId?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        DbStatus: "ready" | "scanning" | "error";
        /** @enum {string} */
        ConnectionState: "connected" | "connecting" | "reconnecting" | "disconnected" | "degraded";
        Project: {
            id: string;
            name: string;
            /** @description Safe, display-only path (never an absolute filesystem path unless necessary). */
            displayPath: string;
            defaultBranch: string;
            activeBranch: string;
            activeCommitHash?: string;
            /** Format: date-time */
            lastScanAt?: string;
            decisionsActiveCount?: number;
            questionsOpenCount?: number;
            dbStatus: components["schemas"]["DbStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        ProjectCreateRequest: {
            path: string;
            name?: string;
        };
        ProjectStatus: {
            projectId: string;
            connection: components["schemas"]["ConnectionState"];
            scanning: boolean;
            /** Format: date-time */
            lastScanAt?: string;
            defaultProvider?: string;
            defaultVoice?: string;
            defaultRate?: number;
            activeBranch: string;
            activeCommitHash?: string;
        };
        /** @enum {string} */
        CommitAnalysisStatus: "pending" | "analyzed" | "failed";
        Commit: {
            hash: string;
            shortHash: string;
            subject: string;
            message: string;
            author: string;
            /** Format: date-time */
            authoredAt: string;
            branch: string;
            changedDocPaths?: string[];
            changedCodePaths?: string[];
            summary?: string;
            decisionsNew?: number;
            questionsOpen?: number;
            questionsResolved?: number;
            analysisStatus: components["schemas"]["CommitAnalysisStatus"];
            analysisProvider?: string;
        };
        CommitPage: {
            items: components["schemas"]["Commit"][];
            nextCursor?: string;
        };
        FileTreeEntry: {
            path: string;
            /** @enum {string} */
            type: "file" | "directory";
            changed?: boolean;
        };
        FileContent: {
            path: string;
            commitHash: string;
            language: string;
            sizeBytes: number;
            lineCount: number;
            truncated: boolean;
            content: string;
            startLine: number;
            endLine: number;
        };
        /** @enum {string} */
        DiffFileStatus: "added" | "modified" | "deleted" | "renamed";
        /** @enum {string} */
        DiffLineType: "added" | "removed" | "context";
        DiffLine: {
            type: components["schemas"]["DiffLineType"];
            content: string;
            oldLineNumber?: number;
            newLineNumber?: number;
        };
        DiffHunk: {
            header: string;
            lines: components["schemas"]["DiffLine"][];
        };
        FileDiff: {
            oldPath?: string;
            newPath: string;
            status: components["schemas"]["DiffFileStatus"];
            commitHash: string;
            parentHash?: string;
            additions: number;
            deletions: number;
            hunks: components["schemas"]["DiffHunk"][];
        };
        /** @enum {string} */
        DecisionStatus: "active" | "superseded" | "revoked" | "candidate";
        /** @enum {string} */
        DecisionExplicitness: "explicit" | "inferred" | "user_confirmed";
        /** @enum {string} */
        DecisionConfidence: "high" | "medium" | "low";
        Decision: {
            id: string;
            title: string;
            description: string;
            status: components["schemas"]["DecisionStatus"];
            explicitness: components["schemas"]["DecisionExplicitness"];
            confidence: components["schemas"]["DecisionConfidence"];
            commitHash: string;
            filePath?: string;
            heading?: string;
            startLine?: number;
            endLine?: number;
            supersedesId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        DecisionDetail: components["schemas"]["Decision"] & {
            supersededByIds?: string[];
            relatedCommitHashes?: string[];
            relatedQuestionIds?: string[];
        };
        /** @enum {string} */
        QuestionStatus: "open" | "resolved" | "dismissed";
        Question: {
            id: string;
            question: string;
            status: components["schemas"]["QuestionStatus"];
            commitHash: string;
            filePath?: string;
            startLine?: number;
            endLine?: number;
            heading?: string;
            /** Format: date-time */
            createdAt: string;
            resolvedCommitHash?: string;
            resolution?: string;
        };
        /** @enum {string} */
        ChatScope: "docs" | "code" | "edit";
        Thread: {
            id: string;
            projectId: string;
            commitHash?: string;
            scope: components["schemas"]["ChatScope"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messageCount: number;
        };
        /** @enum {string} */
        SourceReferenceKind: "document" | "document_diff" | "code" | "decision" | "question" | "conversation";
        SourceReference: {
            id: string;
            kind: components["schemas"]["SourceReferenceKind"];
            path?: string;
            commitHash?: string;
            startLine?: number;
            endLine?: number;
            heading?: string;
            label: string;
            valid: boolean;
        };
        /** @enum {string} */
        ToolActivityStatus: "started" | "completed" | "failed";
        ToolActivity: {
            id: string;
            name: string;
            status: components["schemas"]["ToolActivityStatus"];
            detail?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        /** @enum {string} */
        MessageRole: "user" | "assistant";
        /** @enum {string} */
        MessageStatus: "complete" | "failed" | "cancelled";
        Message: {
            id: string;
            threadId: string;
            role: components["schemas"]["MessageRole"];
            content: string;
            /** Format: date-time */
            createdAt: string;
            scope: components["schemas"]["ChatScope"];
            provider?: string;
            model?: string;
            sources?: components["schemas"]["SourceReference"][];
            toolActivity?: components["schemas"]["ToolActivity"][];
            decisionsDetected?: string[];
            questionsDetected?: string[];
            durationMs?: number;
            status: components["schemas"]["MessageStatus"];
            editProposal?: components["schemas"]["EditProposal"];
            suggestedScope?: components["schemas"]["ChatScope"];
        };
        EditProposalFile: {
            path: string;
            diff: string;
        };
        EditProposal: {
            id: string;
            applied: boolean;
            /** @enum {string} */
            engine: "dev_agent" | "llm";
            files: components["schemas"]["EditProposalFile"][];
        };
        MessagePage: {
            items: components["schemas"]["Message"][];
            nextCursor?: string;
        };
        ChatRunCreateRequest: {
            threadId?: string;
            commitHash: string;
            scope: components["schemas"]["ChatScope"];
            message: string;
            provider?: string;
        };
        /** @enum {string} */
        ChatRunStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        ChatRun: {
            id: string;
            threadId: string;
            status: components["schemas"]["ChatRunStatus"];
        };
        /** @enum {string} */
        ProviderCapability: "conversation" | "structured_output" | "streaming" | "thread_resume" | "repository_access" | "tool_use" | "code_inspection" | "citations";
        /** @enum {string} */
        ProviderTask: "commit_analysis" | "documentation_chat" | "code_inspection" | "document_explanation";
        /** @enum {string} */
        ProviderAvailability: "available" | "unavailable" | "unknown";
        Provider: {
            name: string;
            type: string;
            local: boolean;
            model?: string;
            availability: components["schemas"]["ProviderAvailability"];
            authConfigured: boolean;
            capabilities: components["schemas"]["ProviderCapability"][];
            routedTasks?: components["schemas"]["ProviderTask"][];
        };
        ProviderSettingsUpdateRequest: {
            defaultProvider?: string;
            defaultModel?: string;
            taskRouting?: {
                [key: string]: string;
            };
        };
        Voice: {
            id: string;
            name: string;
            provider: string;
            description?: string;
            language: string;
            recommended: boolean;
            availability: components["schemas"]["ProviderAvailability"];
        };
        SpeakRequest: {
            text: string;
        };
        SpeechSettings: {
            provider: string;
            model?: string;
            voiceId: string;
            language: string;
            rate: number;
            capabilities?: string[];
        };
        VoicePreviewRequest: {
            voiceId: string;
            text?: string;
        };
        VoicePreview: {
            voiceId: string;
            audioUrl: string;
        };
        /** @enum {string} */
        ReadingMode: "verbatim" | "narrate" | "explain";
        AudioSegment: {
            index: number;
            text: string;
            audioUrl: string;
            heading?: string;
        };
        ReadingSession: {
            id: string;
            projectId: string;
            filePath: string;
            commitHash: string;
            voice: string;
            mode: components["schemas"]["ReadingMode"];
            segments: components["schemas"]["AudioSegment"][];
            /** Format: date-time */
            createdAt: string;
            stale: boolean;
        };
        ReadingSessionCreateRequest: {
            filePath: string;
            commitHash: string;
            voice?: string;
            mode: components["schemas"]["ReadingMode"];
            skipCode: boolean;
            changesOnly: boolean;
            startLine?: number;
            endLine?: number;
        };
        Diagnostics: {
            backendVersion: string;
            uptimeSeconds: number;
            database: {
                status: string;
                path: string;
            };
            providers: components["schemas"]["Provider"][];
            speechProviders: components["schemas"]["Provider"][];
            lastError?: string;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        CommitHash: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Project"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getProjectStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStatus"];
                };
            };
        };
    };
    scanProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStatus"];
                };
            };
        };
    };
    listCommits: {
        parameters: {
            query?: {
                branch?: string;
                cursor?: string;
                status?: components["schemas"]["CommitAnalysisStatus"];
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitPage"];
                };
            };
        };
    };
    getCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                commitHash: components["parameters"]["CommitHash"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listFiles: {
        parameters: {
            query: {
                commit: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["FileTreeEntry"][];
                    };
                };
            };
        };
    };
    getFileContent: {
        parameters: {
            query: {
                path: string;
                commit: string;
                startLine?: number;
                endLine?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getFileDiff: {
        parameters: {
            query: {
                path: string;
                commit: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDiff"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                status?: components["schemas"]["DecisionStatus"];
                explicitness?: components["schemas"]["DecisionExplicitness"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Decision"][];
                    };
                };
            };
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                decisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                status?: components["schemas"]["QuestionStatus"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Question"][];
                    };
                };
            };
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listThreads: {
        parameters: {
            query?: {
                commit?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Thread"][];
                    };
                };
            };
        };
    };
    listThreadMessages: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
        };
    };
    createChatRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRunCreateRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRun"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    applyEditProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditProposal"];
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRun"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of RunEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRun"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateProviderSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStatus"];
                };
            };
        };
    };
    listSpeechProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Provider"][];
                    };
                };
            };
        };
    };
    listVoices: {
        parameters: {
            query?: {
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Voice"][];
                    };
                };
            };
        };
    };
    previewVoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoicePreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePreview"];
                };
            };
            429: components["responses"]["Problem"];
        };
    };
    speakText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakRequest"];
            };
        };
        responses: {
            /** @description audio stream, media type depends on the configured provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    updateSpeechSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeechSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechSettings"];
                };
            };
        };
    };
    createReadingSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
        };
    };
    getReadingSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    stopReadingSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadingSegmentAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description audio/mpeg stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostics"];
                };
            };
        };
    };
}
