/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdChatRouteImport } from './routes/projects/$projectId/chat'
import { Route as ProjectsProjectIdDecisionsRouteImport } from './routes/projects/$projectId/decisions'
import { Route as ProjectsProjectIdFilesRouteImport } from './routes/projects/$projectId/files'
import { Route as ProjectsProjectIdOverviewRouteImport } from './routes/projects/$projectId/overview'
import { Route as ProjectsProjectIdQuestionsRouteImport } from './routes/projects/$projectId/questions'
import { Route as ProjectsProjectIdSettingsRouteRouteImport } from './routes/projects/$projectId/settings/route'
import { Route as ProjectsProjectIdTimelineRouteImport } from './routes/projects/$projectId/timeline'
import { Route as ProjectsProjectIdDecisionsDecisionIdRouteImport } from './routes/projects/$projectId/decisions.$decisionId'
import { Route as ProjectsProjectIdSettingsDiagnosticsRouteImport } from './routes/projects/$projectId/settings/diagnostics'
import { Route as ProjectsProjectIdSettingsGeneralRouteImport } from './routes/projects/$projectId/settings/general'
import { Route as ProjectsProjectIdSettingsProvidersRouteImport } from './routes/projects/$projectId/settings/providers'
import { Route as ProjectsProjectIdSettingsSpeechRouteImport } from './routes/projects/$projectId/settings/speech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdChatRoute = ProjectsProjectIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdDecisionsRoute =
  ProjectsProjectIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdFilesRoute = ProjectsProjectIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdOverviewRoute =
  ProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdQuestionsRoute =
  ProjectsProjectIdQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdSettingsRouteRoute =
  ProjectsProjectIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTimelineRoute =
  ProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdDecisionsDecisionIdRoute =
  ProjectsProjectIdDecisionsDecisionIdRouteImport.update({
    id: '/$decisionId',
    path: '/$decisionId',
    getParentRoute: () => ProjectsProjectIdDecisionsRoute,
  } as any)
const ProjectsProjectIdSettingsDiagnosticsRoute =
  ProjectsProjectIdSettingsDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => ProjectsProjectIdSettingsRouteRoute,
  } as any)
const ProjectsProjectIdSettingsGeneralRoute =
  ProjectsProjectIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProjectsProjectIdSettingsRouteRoute,
  } as any)
const ProjectsProjectIdSettingsProvidersRoute =
  ProjectsProjectIdSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => ProjectsProjectIdSettingsRouteRoute,
  } as any)
const ProjectsProjectIdSettingsSpeechRoute =
  ProjectsProjectIdSettingsSpeechRouteImport.update({
    id: '/speech',
    path: '/speech',
    getParentRoute: () => ProjectsProjectIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/decisions': typeof ProjectsProjectIdDecisionsRouteWithChildren
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/questions': typeof ProjectsProjectIdQuestionsRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/decisions/$decisionId': typeof ProjectsProjectIdDecisionsDecisionIdRoute
  '/projects/$projectId/settings/diagnostics': typeof ProjectsProjectIdSettingsDiagnosticsRoute
  '/projects/$projectId/settings/general': typeof ProjectsProjectIdSettingsGeneralRoute
  '/projects/$projectId/settings/providers': typeof ProjectsProjectIdSettingsProvidersRoute
  '/projects/$projectId/settings/speech': typeof ProjectsProjectIdSettingsSpeechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/decisions': typeof ProjectsProjectIdDecisionsRouteWithChildren
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/questions': typeof ProjectsProjectIdQuestionsRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/decisions/$decisionId': typeof ProjectsProjectIdDecisionsDecisionIdRoute
  '/projects/$projectId/settings/diagnostics': typeof ProjectsProjectIdSettingsDiagnosticsRoute
  '/projects/$projectId/settings/general': typeof ProjectsProjectIdSettingsGeneralRoute
  '/projects/$projectId/settings/providers': typeof ProjectsProjectIdSettingsProvidersRoute
  '/projects/$projectId/settings/speech': typeof ProjectsProjectIdSettingsSpeechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRouteRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/decisions': typeof ProjectsProjectIdDecisionsRouteWithChildren
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/questions': typeof ProjectsProjectIdQuestionsRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/decisions/$decisionId': typeof ProjectsProjectIdDecisionsDecisionIdRoute
  '/projects/$projectId/settings/diagnostics': typeof ProjectsProjectIdSettingsDiagnosticsRoute
  '/projects/$projectId/settings/general': typeof ProjectsProjectIdSettingsGeneralRoute
  '/projects/$projectId/settings/providers': typeof ProjectsProjectIdSettingsProvidersRoute
  '/projects/$projectId/settings/speech': typeof ProjectsProjectIdSettingsSpeechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/agents/'
    | '/projects/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/decisions'
    | '/projects/$projectId/files'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/questions'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/'
    | '/projects/$projectId/decisions/$decisionId'
    | '/projects/$projectId/settings/diagnostics'
    | '/projects/$projectId/settings/general'
    | '/projects/$projectId/settings/providers'
    | '/projects/$projectId/settings/speech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/projects'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/decisions'
    | '/projects/$projectId/files'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/questions'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId'
    | '/projects/$projectId/decisions/$decisionId'
    | '/projects/$projectId/settings/diagnostics'
    | '/projects/$projectId/settings/general'
    | '/projects/$projectId/settings/providers'
    | '/projects/$projectId/settings/speech'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/agents/'
    | '/projects/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/decisions'
    | '/projects/$projectId/files'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/questions'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/'
    | '/projects/$projectId/decisions/$decisionId'
    | '/projects/$projectId/settings/diagnostics'
    | '/projects/$projectId/settings/general'
    | '/projects/$projectId/settings/providers'
    | '/projects/$projectId/settings/speech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/chat': {
      id: '/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProjectsProjectIdChatRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/decisions': {
      id: '/projects/$projectId/decisions'
      path: '/decisions'
      fullPath: '/projects/$projectId/decisions'
      preLoaderRoute: typeof ProjectsProjectIdDecisionsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/files': {
      id: '/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof ProjectsProjectIdFilesRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/overview': {
      id: '/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof ProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/questions': {
      id: '/projects/$projectId/questions'
      path: '/questions'
      fullPath: '/projects/$projectId/questions'
      preLoaderRoute: typeof ProjectsProjectIdQuestionsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/timeline': {
      id: '/projects/$projectId/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/timeline'
      preLoaderRoute: typeof ProjectsProjectIdTimelineRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/decisions/$decisionId': {
      id: '/projects/$projectId/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/projects/$projectId/decisions/$decisionId'
      preLoaderRoute: typeof ProjectsProjectIdDecisionsDecisionIdRouteImport
      parentRoute: typeof ProjectsProjectIdDecisionsRoute
    }
    '/projects/$projectId/settings/diagnostics': {
      id: '/projects/$projectId/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/projects/$projectId/settings/diagnostics'
      preLoaderRoute: typeof ProjectsProjectIdSettingsDiagnosticsRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRouteRoute
    }
    '/projects/$projectId/settings/general': {
      id: '/projects/$projectId/settings/general'
      path: '/general'
      fullPath: '/projects/$projectId/settings/general'
      preLoaderRoute: typeof ProjectsProjectIdSettingsGeneralRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRouteRoute
    }
    '/projects/$projectId/settings/providers': {
      id: '/projects/$projectId/settings/providers'
      path: '/providers'
      fullPath: '/projects/$projectId/settings/providers'
      preLoaderRoute: typeof ProjectsProjectIdSettingsProvidersRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRouteRoute
    }
    '/projects/$projectId/settings/speech': {
      id: '/projects/$projectId/settings/speech'
      path: '/speech'
      fullPath: '/projects/$projectId/settings/speech'
      preLoaderRoute: typeof ProjectsProjectIdSettingsSpeechRouteImport
      parentRoute: typeof ProjectsProjectIdSettingsRouteRoute
    }
  }
}

interface ProjectsProjectIdSettingsRouteRouteChildren {
  ProjectsProjectIdSettingsDiagnosticsRoute: typeof ProjectsProjectIdSettingsDiagnosticsRoute
  ProjectsProjectIdSettingsGeneralRoute: typeof ProjectsProjectIdSettingsGeneralRoute
  ProjectsProjectIdSettingsProvidersRoute: typeof ProjectsProjectIdSettingsProvidersRoute
  ProjectsProjectIdSettingsSpeechRoute: typeof ProjectsProjectIdSettingsSpeechRoute
}

const ProjectsProjectIdSettingsRouteRouteChildren: ProjectsProjectIdSettingsRouteRouteChildren =
  {
    ProjectsProjectIdSettingsDiagnosticsRoute:
      ProjectsProjectIdSettingsDiagnosticsRoute,
    ProjectsProjectIdSettingsGeneralRoute:
      ProjectsProjectIdSettingsGeneralRoute,
    ProjectsProjectIdSettingsProvidersRoute:
      ProjectsProjectIdSettingsProvidersRoute,
    ProjectsProjectIdSettingsSpeechRoute: ProjectsProjectIdSettingsSpeechRoute,
  }

const ProjectsProjectIdSettingsRouteRouteWithChildren =
  ProjectsProjectIdSettingsRouteRoute._addFileChildren(
    ProjectsProjectIdSettingsRouteRouteChildren,
  )

interface ProjectsProjectIdDecisionsRouteChildren {
  ProjectsProjectIdDecisionsDecisionIdRoute: typeof ProjectsProjectIdDecisionsDecisionIdRoute
}

const ProjectsProjectIdDecisionsRouteChildren: ProjectsProjectIdDecisionsRouteChildren =
  {
    ProjectsProjectIdDecisionsDecisionIdRoute:
      ProjectsProjectIdDecisionsDecisionIdRoute,
  }

const ProjectsProjectIdDecisionsRouteWithChildren =
  ProjectsProjectIdDecisionsRoute._addFileChildren(
    ProjectsProjectIdDecisionsRouteChildren,
  )

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdSettingsRouteRoute: typeof ProjectsProjectIdSettingsRouteRouteWithChildren
  ProjectsProjectIdChatRoute: typeof ProjectsProjectIdChatRoute
  ProjectsProjectIdDecisionsRoute: typeof ProjectsProjectIdDecisionsRouteWithChildren
  ProjectsProjectIdFilesRoute: typeof ProjectsProjectIdFilesRoute
  ProjectsProjectIdOverviewRoute: typeof ProjectsProjectIdOverviewRoute
  ProjectsProjectIdQuestionsRoute: typeof ProjectsProjectIdQuestionsRoute
  ProjectsProjectIdTimelineRoute: typeof ProjectsProjectIdTimelineRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdSettingsRouteRoute:
      ProjectsProjectIdSettingsRouteRouteWithChildren,
    ProjectsProjectIdChatRoute: ProjectsProjectIdChatRoute,
    ProjectsProjectIdDecisionsRoute:
      ProjectsProjectIdDecisionsRouteWithChildren,
    ProjectsProjectIdFilesRoute: ProjectsProjectIdFilesRoute,
    ProjectsProjectIdOverviewRoute: ProjectsProjectIdOverviewRoute,
    ProjectsProjectIdQuestionsRoute: ProjectsProjectIdQuestionsRoute,
    ProjectsProjectIdTimelineRoute: ProjectsProjectIdTimelineRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
